### ISSUE TITLE
ItemAnimation has no effect

### ISSUE THREAD

**Issue by TinasheMzondiwa** [Malinskiy/SuperRecyclerView#10]
I'm trying to add ItemAnimations and there seem to be no effect.
I tried .getRecyclerView.addItemAnimator()
Even the default ItemAnimator has no effect

**Comment by Malinskiy** [comment]
Hi @TinasheMzondiwa! Which animations do you not see? Adding and removing are definitely in the DefaultItemAnimator. 
Which version of Android do you use? I believe DefaultItemAnimator is using Android animation API so animations are only available to API 11+.

**Comment by Trikke** [comment]
Are you sure you need an itemAnimator? The default itemAnimator works fine, but i suspect you want to animate views as they appear, not items. In which case you need to animate the itemviews in your adapter, see https://gist.github.com/frogermcs/61b885eb2e44e0d2d61f#file-feedadapter-java for an example.

**Comment by TinasheMzondiwa** [comment]
@Trikke that is indeed what I wanted. Thank you very much.
