### ISSUE TITLE
Retrieve the EmptyView layout

### ISSUE THREAD

**Issue by Christophe668** [Malinskiy/SuperRecyclerView#11]
Is it possible to retrieve the empty view via a getter?
It would be nice to change the content of the view dynamically and reuse the empty layout for other SuperRecyclerView.

Thanks !

**Comment by Malinskiy** [comment]
Hi @Christophe668! I've introduced getters for empty, progress and moreprogress layout in 4db166bf670e678969387e63aaf10bfd763ce587. Fetch the new v1.1.0.

Thanks for the issue.
