### ISSUE TITLE
[Question] How to hide progress loader

### ISSUE THREAD

**Issue by mdtuyen** [Malinskiy/SuperRecyclerView#113]
I custom dapter to make last item as progress bar to show that I loading.
So that I do't need progress loadmore of this library.

How do I remove it ?

**Comment by enginebai** [comment]
Try to use `mRecyclerView.hideMoreProgress();`

**Comment by mdtuyen** [comment]
it will re-show in later load.
Current I custom view loader by an View with height = 1px
