### ISSUE TITLE
Disable refresh.

### ISSUE THREAD

**Issue by Wolftein** [Malinskiy/SuperRecyclerView#18]
Hi,

I'm using refresh feature only when failed to retrieve data from a network source and disabling it when data has been received. Calling setRefreshListener(null) should disable the listener instead of enabling it.

**Comment by AssemblyXiang** [comment]
I read source and find the method "getSwipeToRefresh().setRefreshing(false)" can stop fresh process,hope to help you!

**Comment by Wolftein** [comment]
That worked, thanks!
