### ISSUE TITLE
setOnItemClickListener 

### ISSUE THREAD

**Issue by patelakshay13890** [Malinskiy/SuperRecyclerView#21]
recycleview.setOnItemClickListener(new OnItemClickListener() {							@Override
public void onItemClick(AdapterView<?> parent,View view, int position, long id) {
});
}

Is there any method like this ?
so we can access it in out Activity ?

**Comment by Malinskiy** [comment]
Hi @patelakshay13890

Please look at the [implementation](https://github.com/Malinskiy/SuperRecyclerView/blob/master/SuperRecyclerView-sample/src/main/java/com/malinskiy/superrecyclerview/sample/RecyclerUtils.java) of generic **OnItemTouchListener** and [this](https://github.com/Malinskiy/SuperRecyclerView/blob/master/SuperRecyclerView-sample/src/main/java/com/malinskiy/superrecyclerview/sample/SwipeActivity.java#L33) for example
