### ISSUE TITLE
enable / disable android attribute for layout_moreProgress

### ISSUE THREAD

**Issue by LOG-TAG** [Malinskiy/SuperRecyclerView#24]
For example if I need to remove or disable the features like swipe to refresh , more progress bar or any other attribute we need Attributes or at least programmatical  way to do that  

Thanks

**Comment by Malinskiy** [comment]
@LOG-TAG,

the swipe to refresh layout is disabled by default. If you need to modify it during runtime you can call `getSwipeToRefresh()`.

If you want to disable any layouts you can write a custom layout based on [basic one](https://github.com/Malinskiy/SuperRecyclerView/blob/master/SuperRecyclerView/src/main/res/layout/layout_recyclerview_horizontalscroll.xml), that way you can disable the features you don't actually need.

If you want to disable the more progress bar in runtime you just have to call hideMoreProgress() in your onMoreAsked() callback when appropriate.

**Comment by LOG-TAG** [comment]
Thanks :)
