### ISSUE TITLE
NullPointerExecption in RecyclerView when calling stopScroll() method

### ISSUE THREAD

**Issue by TiagoMota** [Malinskiy/SuperRecyclerView#25]
Hi,

So me and the team have been using this library for our project and after a while we runned into the situation stated in this StackOverflow Question: http://stackoverflow.com/a/26908738
Our app started crashing randomly giving this error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.RecyclerView$LayoutManager.stopSmoothScroller()' on a null object reference
```
Then we noticed it was happening mainly when returning back to a SuperRecyclerView that was empty but know needed to display some content. But the issue happen on other situations that required the initialization of the SuperRecyclerView.

We solved it by applying the solution given in the SA Question in a forked version of this library, ending up replacing the RecyclerView variable for HotFixRecyclerView in the SuperRecyclerView class and layouts.
Can you introduce this error handling in the library? Or do you have other suggestion on how to bypass this issue?

Thanks, and great work with the library!

**Comment by Malinskiy** [comment]
Hi @TiagoMota!

The way I see it it's a bug of RecyclerView, so the relevant issue is with the [RecyclerView implementation](https://code.google.com/p/android/issues/detail?id=79244). Did you try out the suggested fix to always setup the LayoutManager in onCreate/onCreateView? That may reduce the window for this NPE error.

**Comment by TiagoMota** [comment]
Yes, our calls to set the LayoutManger were always on the onCreate/OnCreateView. It does not happen every time but sometimes. So for the time being we solved it by integrating that try/catch for the NPE, but I agree with you, this is an issue of the RecyclerView implementation itself. I just wanted to get your opinion, since this might had happen before to you or someone else, and our team could be missing some other solution. Thanks for the quick answer @Malinskiy !

**Comment by Malinskiy** [comment]
Updated to support 22.2.1. Should be fixed according to [this](https://code.google.com/p/android/issues/detail?id=79244)
