### ISSUE TITLE
Ripple touch effect

### ISSUE THREAD

**Issue by amrsilva** [Malinskiy/SuperRecyclerView#29]
Hi!

How I can add a touch feedback event to list?
I'm trying to add the event to SuperRecyclerView but nothing is working.

**Comment by amrsilva** [comment]
Hi! I found this link that help me.

http://blog.stylingandroid.com/material-part-5/

**Comment by SovcikJoe** [comment]
That didn't work for me as then the swipe-to-delete didn't work.
