### ISSUE TITLE
set progress bar

### ISSUE THREAD

**Issue by hamzux** [Malinskiy/SuperRecyclerView#32]
Hi, 
is there a way to set a custom progress bar for the library? 

I wanted to use com.pnikosis.materialishprogress.ProgressWheel with SuperRecyclerView but didn't figure out how? 

Thanks

**Comment by jimgswang** [comment]
I peeked at the source and saw  L92:          
mProgressId = a.getResourceId(R.styleable.superrecyclerview_layout_progress, R.layout.layout_progress);

I tested with 
    <com.malinskiy.superrecyclerview.SuperRecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_progress="@layout/test"
        >

and it works

**Comment by Malinskiy** [comment]
Glad you've found necessary attributes @hamzux  :)
