### ISSUE TITLE
SwipeToDismiss with undo layout ?

### ISSUE THREAD

**Issue by semenoh** [Malinskiy/SuperRecyclerView#4]
Hi,
First of all I want to thank you guys for grate library.

I am playing around with SwipeToDismiss functionality and I'm just wondering if there is a way to sat a layout for item after it is swiped out in order to place undo button or show progress while performing network request ?

Thanks.

**Comment by Malinskiy** [comment]
@semenoh I believe it's done via ef6574bd2a9e5f3d10e54089d6f6750ea61a2a9d in v1.1.0. If not please reopen.
