### ISSUE TITLE
custom progressbar

### ISSUE THREAD

**Issue by raviteja83** [Malinskiy/SuperRecyclerView#51]
I want to show custom Progressbar.How can i override the existing one?

**Comment by diegoRodriguezAguila** [comment]
I guess you can override it in this layout https://github.com/Malinskiy/SuperRecyclerView/blob/master/SuperRecyclerView/src/main/res/layout/layout_progress.xml

**Comment by Malinskiy** [comment]
Hi @raviteja83,

you can supply a progress layout like this:

```xml
  <com.malinskiy.superrecyclerview.SuperRecyclerView
            xmlns:app="http://schemas.android.com/apk/res-auto"
            ...
            app:layout_progress ="@layout/custom_progress_view"
            .../>
```

without recompiling
