### ISSUE TITLE
How to remove circular progress bar at bottom of recyclerview

### ISSUE THREAD

**Issue by SachinRana028** [Malinskiy/SuperRecyclerView#54]
I am using recycler view inside fragment after loading data the circular progress bar is still visible at  bottom . I want after loading data the circular progress bar hides
this is my fragment layout please help me 

      <?xml version="1.0" encoding="utf-8"?>
      <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
         android:layout_width="match_parent"
        android:layout_height="match_parent">

    <com.malinskiy.superrecyclerview.SuperRecyclerView
      android:id="@+id/list"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:recyclerClipToPadding="false"
      app:recyclerPadding="16dp"
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto"
    />
    </RelativeLayout>

**Comment by Malinskiy** [comment]
Hi @SachinRana028,

you can call `hideProgress` or `hideMoreProgress` for hiding the progress bar accordingly.

**Comment by SachinRana028** [comment]
Thanks @Malinskiy

**Comment by subhasishnath45** [comment]
but from which method ???

I found out In case of fetching JSON data by Volley library, 
i did this inside onResponse(JSONArray response) method:


                    if(response.length()>0){
                        progressbar.setVisibility(ProgressBar.GONE);
                    }
