### ISSUE TITLE
OnMoreListener gets triggerred when scrolling up 

### ISSUE THREAD

**Issue by chaitanya79** [Malinskiy/SuperRecyclerView#60]
I am trying to user super recycler view to load a list of messages from the server and when I reach the end of pages and start scrolling up again a call is getting triggered to load more messages.

**Comment by hush881025** [comment]
When I use  mRecycler.setupMoreListener(this, 1) ; the onMoreAsked would be called 10 times untils 
  ((totalItemCount - lastVisibleItemPosition) <= ITEM_LEFT_TO_LOAD_MORE ||
                        (totalItemCount - lastVisibleItemPosition) == 0 && totalItemCount > visibleItemCount)
                        && !isLoadingMore)   return false;  I guess the second param in setupMoreListener is useless！

**Comment by chaitanya79** [comment]
Hi @hush881025 Does the above mentioned issue exist with ultimate recyclerview ?

**Comment by hush881025** [comment]
yes,it dose

**Comment by chaitanya79** [comment]
@hush881025 Thank you.

**Comment by hush881025** [comment]
you are welcome

**Comment by youzai001** [comment]
Maybe we should check whether it's scrolling down or up.
just change SuperRecyclerView.java on line 145 as blow:

@Override
public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
	super.onScrolled(recyclerView, dx, dy);

	if (dy > 5) { // only process it when scrolled down
		processOnMore();
	}

	if (mExternalOnScrollListener != null)
		mExternalOnScrollListener.onScrolled(recyclerView, dx, dy);
	if (mSwipeDismissScrollListener != null)
		mSwipeDismissScrollListener.onScrolled(recyclerView, dx, dy);
}

**Comment by raviteja06** [comment]
I did a small hack to get rid of this problem. I replaced the load more layout with a dummy 0dp layout. and after that i had a custom progress dialog in my layout which starts/stops when calls server.
