### ISSUE TITLE
layout_recyclerSelector vs recyclerPadding

### ISSUE THREAD

**Issue by Chainfire** [Malinskiy/SuperRecyclerView#8]
layout_recyclerSelector needs to be set for recyclerPadding to work. It is unclear why this is or should be - I just want some padding. Also layout_recyclerSelector doesn't actually seem to do anything either way.

**Comment by Malinskiy** [comment]
Hi @Chainfire! Sorry for the mixup, I've fixed the issue in ef6574bd2a9e5f3d10e54089d6f6750ea61a2a9d by removing selector, it really doesn't do anything here :) Use the new v1.1.0 and n'joy :)
