### ISSUE TITLE
no scrollbars

### ISSUE THREAD

**Issue by Chainfire** [Malinskiy/SuperRecyclerView#9]
Just converting from a basic RecyclerView to SuperRecyclerView, using only the dismiss functionality as an extra. Just noticed scrollbars are gone:

```   
<com.malinskiy.superrecyclerview.SuperRecyclerView
        android:id="@+id/recycler_view"
        android:scrollbars="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:scrollbarStyle="outsideOverlay"
        app:recyclerClipToPadding="false"
        app:recyclerPaddingTop="8dp"
        app:recyclerPaddingBottom="8dp"
        app:layout_recyclerSelector="?android:attr/selectableItemBackground" />
```

Tried various changes to bring them back, but to no avail.

**Comment by Chainfire** [comment]
I learned from here http://stackoverflow.com/questions/27056379/is-there-any-way-to-enable-scrollbars-for-recyclerview-in-code that enabling the scrollbars through code isn't (easily) possible, and it has to be done through XML.

The solution is to copy your  `layout_progress_recyclerview.xml`, add `android:scrollbars="vertical"` to the `RecyclerView` tag in the copy, then add this new layout reference as `app:mainLayoutId` to the `SuperRecyclerView` tag. That works, though a bit cumbersome. 

If not fixed, then perhaps it should be documented. If it already was and I missed it, sorry :)

**Comment by Malinskiy** [comment]
@Chainfire! After fighting with enabling scrollbars from code I ended up fixing the issue by introducing different layouts. See https://github.com/Malinskiy/SuperRecyclerView#scrollbars. Thanks for the issue! :)
